
# services:
#   backend:
#     build: !reset null
#     image: dieuxuanhien/discord-demo-backend:latest

#   frontend:
#     build: !reset null
#     image: dieuxuanhien/discord-demo-frontend:latest
